queues:
  - id: 1
    servers: 2
    capacity: 3
    arrival:
      min: 1.0
      max: 4.0
    service:
      min: 3.0
      max: 4.0
  - id: 2
    servers: 1
    capacity: 5
    service:
      min: 2.0
      max: 3.0